Repository WildCodeSchool/lyon-js-sept2020-p3-lafrica-api, pull requests merged in 2020-12, with the labels that each got.

#1 init db
  migrations/20201208135848-initProjet3Db.js
  migrations/sqls/20201208135848-initProjet3Db-down.sql
  migrations/sqls/20201208135848-initProjet3Db-up.sql
Labels: Ready for Prod

#2 Init route
  .gitignore
  app.js
  controllers/campaigns.js
  migrations/20201203132111-initDB.js
  migrations/20201208135848-initProjet3Db.js
  migrations/sqls/20201203132111-initDB-down.sql
  migrations/sqls/20201203132111-initDB-up.sql
  migrations/sqls/20201208135848-initProjet3Db-down.sql
  migrations/sqls/20201208135848-initProjet3Db-up.sql
  models/campaigns.js
  output.mp3
  package-lock.json
  package.json
  routes/campaigns.js
  routes/index.js
  services/textToSpeech.js
Labels: Ready for Prod

#4 Init route
  .gitignore
  app.js
  controllers/campaigns.js
  models/campaigns.js
  output.mp3
  package-lock.json
  package.json
  routes/campaigns.js
  routes/index.js
  services/textToSpeech.js
Labels: Fixed - ready for prod

#6 Auth
  .env.sample
  .gitignore
  app.js
  controllers/auth.js
  controllers/users.js
  db.js
  env.js
  middlewares/requireRequestBody.js
  migrations/20201216083543-updatedb.js
  migrations/sqls/20201216083543-updatedb-down.sql
  migrations/sqls/20201216083543-updatedb-up.sql
  models/campaigns.js
  models/users.js
  output.mp3
  package-lock.json
  package.json
  routes/auth.js
  routes/index.js
  routes/users.js
  sessionStore.js
Labels: WIP
